main: com.solitudecraft.solitudeessentials.SolitudeEssentials
name: SolitudeEssentials
version: 0.1
author: DragonSlayer1920
description: Solitude Craft essentials.

commands:
  broadcast:
    aliases: [b, br]
  feed:
    aliases: [food]
  fly:
  gamemode:
    aliases: [gm]
  heal:
    aliases: [health, h]
  time:
    aliases: [settime]
  message:
    aliases: [msg, pm, dm, m, w, whisper]
  viewmessage:
    aliases: [socialspy, viewmsg, viewpm, msgspy, pmspy]
  lookupmessage:
    aliases: [lookupmsg, messagelookup, msglookup, ml]
  teleport:
  tp:
    aliases: [tport]
  teleporthere:
    aliases: [tphere]
  help:
  setwarp:
    aliases: [swarp, cwarp, createwarp, newwarp]
  warp:
    aliases: [w]
  deletewarp:
    aliases: [dwarp, delwarp, removewarp]
  createbuttonwarp:
    aliases: [createbwarp, createbutton, cbwarp, cbutton]
  deletebuttonwarp:
    aliases: [delbuttonwarp, delbwarp, delbutton, dbutton]
  weather: